import 'blockly/blocks'; // default blocks

import { BlocklierCustomBlock } from '../blocklier-models';
import {
  AppAutojsBlock,
  AppEditFileBlock,
  AppGetAppNameBlock,
  AppGetPackageNameBlock,
  AppLaunchAppBlock,
  AppLaunchBlock,
  AppOpenAppSettingBlock,
  AppOpenUrlBlock,
  AppSendEmailBlock,
  AppStartActivityBlock,
  AppUninstallBlock,
  AppVersionCodeBlock,
  AppVersionNameBlock,
  AppViewFileBlock,
} from './app.blocks';
import {
  AutoRootBlock,
  AutoRootInActiveWindowBlock,
  AutoServiceBlock,
  AutoSetFlagsBlock,
  AutoSetModeBlock,
  AutoSetWindowFilterBlock,
  AutoWaitForBlock,
  AutoWindowsBlock,
} from './auto.blocks';
import {
  ConsoleClearBlock,
  ConsoleConfigBackupSizeBlock,
  ConsoleConfigBlock,
  ConsoleConfigFilePatternBlock,
  ConsoleConfigFileSizeBlock,
  ConsoleConfigLevelBlock,
  ConsoleConfigPathBlock,
  ConsoleOutputBlock,
  ConsoleSetPositionBlock,
  ConsoleSetSizeBlock,
  ConsoleShowBlock,
  ConsoleTimeBlock,
} from './console.blocks';
import { ListsGetBlock, ListsSetBlock } from './lists.blocks';

BlocklierCustomBlock.use([
  AppAutojsBlock,
  AppEditFileBlock,
  AppGetAppNameBlock,
  AppGetPackageNameBlock,
  AppLaunchAppBlock,
  AppLaunchBlock,
  AppOpenAppSettingBlock,
  AppOpenUrlBlock,
  AppSendEmailBlock,
  AppStartActivityBlock,
  AppUninstallBlock,
  AppVersionCodeBlock,
  AppVersionNameBlock,
  AppViewFileBlock,

  AutoRootBlock,
  AutoRootInActiveWindowBlock,
  AutoServiceBlock,
  AutoSetFlagsBlock,
  AutoSetModeBlock,
  AutoSetWindowFilterBlock,
  AutoWaitForBlock,
  AutoWindowsBlock,

  ConsoleClearBlock,
  ConsoleConfigBackupSizeBlock,
  ConsoleConfigBlock,
  ConsoleConfigFilePatternBlock,
  ConsoleConfigFileSizeBlock,
  ConsoleConfigLevelBlock,
  ConsoleConfigPathBlock,
  ConsoleOutputBlock,
  ConsoleSetPositionBlock,
  ConsoleSetSizeBlock,
  ConsoleShowBlock,
  ConsoleTimeBlock,

  ListsGetBlock,
  ListsSetBlock,
]);
